name: gripy becnhmark Tests

on:
  push
  # schedule:
  #   - cron:  '0 0 * * *'

jobs:
  unit_tests:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, ]
        python: [3.6, 3.7,]
    steps:
    - uses: actions/checkout@v1
      with:
        lfs: True
    - uses: goanpeca/setup-miniconda@v1
      with:
        auto-update-conda: true
        python-version: ${{ matrix.python }}

    - name: ubuntu install fortran
      run: sudo apt install gfortran
      if: matrix.os == 'ubuntu-latest'

    - name: run install and tests
      run: |
        ls -ltr tests/data
        conda install -c conda-forge cfgrib pygrib
        pip install .
        python benchmarks/read_gfs.py
