name: gripy becnhmark Tests

on:
  push
  # schedule:
  #   - cron:  '0 0 * * *'

jobs:
  unit_tests:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, ]
        python: [3.6, 3.7,]
    steps:
    - uses: actions/checkout@v1
    - uses: goanpeca/setup-miniconda@v1
      with:
        auto-update-conda: true
        python-version: ${{ matrix.python }}
    - shell: bash -l {0}
      run: |
        conda install -c conda-forge cfgrib pygrib
        pip install gripy
        python benchmarks/read_gfs.py
