name: gripy Unit Tests

on: [push]

jobs:
  unit_tests:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [  macos-10.15 ]
        python: [ 3.7, ]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}

    - name: ubuntu install fortran
      run: sudo apt install gfortran
      if: matrix.os == 'ubuntu-latest'

    - name: Fix Conda permissions on macOS
      run: |
        sudo chown -R $UID $CONDA
        echo $SHELL
        $CONDA/bin/conda init bash
      if: matrix.os == 'macos-10.15'

    - name: macos install dependencies
      env:
        DYLD_FALLBACK_LIBRARY_PATH: $CONDA/lib
      run: |
        $CONDA/bin/conda install gfortran_osx-64 numpy wheel
        ln -s $CONDA/bin/gfortran /usr/local/bin/gfortran
        $CONDA/bin/python -m pip install .
        $CONDA/bin/python -m pip install -r requirements-test.txt
        $CONDA/bin/python -m pip install delocate
        $CONDA/bin/python setup.py bdist_wheel
        ln -s $CONDA/lib @rpath
        echo "List delocate"
        $CONDA/bin/delocate-listdeps dist/gripy-*
        echo "Start delocate"
        $CONDA/bin/delocate-wheel -w fixed_wheels -v  dist/gripy-*
    - uses: actions/upload-artifact@v2
      with:
        name: 'Artifacts-V2'
        path: './fixed_wheels'
      if: matrix.os == 'macos-10.15'

    - name: macos run tests
      run: $CONDA/bin/pytest tests/
      if: matrix.os == 'macos-10.15'

    - name: windows install fortran
      run: |
        choco install mingw
        pip install numpy==1.15
      if: matrix.os == 'windows-latest'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .
        pip install -r requirements-test.txt
      if: matrix.os != 'macos-10.15'

    - name: Test with pytest
      run: |
        pip install pytest
        pytest tests/
      if: matrix.os != 'macos-10.15'
