name: gripy Unit Tests

on: [push]

jobs:
  unit_tests:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-12 ]
        python: [3.7, 3.8, 3.9, "3.10"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python }}

    - name: ubuntu install fortran
      run: sudo apt install gfortran
      if: matrix.os == 'ubuntu-latest'

    - name: macos install fortran
      run: |
        brew reinstall gcc  
      # reinstalling gcc installs gfortran which is missing by default
      if: matrix.os == 'macos-12'

    - name: windows install fortran
      run: |
        choco install mingw
        pip install numpy==1.15
      if: matrix.os == 'windows-latest'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .
        pip install -r requirements-test.txt

    - name: Test with pytest
      run: |
        pip install pytest
        pytest tests/
