name: gripy Unit Tests

on: [push]

jobs:
  unit_tests:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python: [3.6, 3.7, 3.8,]

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python }}
    
    - name: apt Install fortran
      run: sudo apt install gfortran
      if: matrix.os == 'ubuntu-latest'
    - name:  brew install gfortran
      run: brew install gfortran
      if: matrix.os == 'macos-latest'
    - name:  choco install gfortran
      run: choco install gfortran
      if: matrix.os == 'windows-latest'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .
        pip install -r requirements-test.txt
    - name: Test with pytest
      run: |
        pip install pytest
        pytest tests/
