name: gripy Unit Tests

on: [push]

jobs:
  unit_tests:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-10.15 ]
        python: [3.7]

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python }}
    
    - name: ubuntu install fortran
      run: sudo apt install gfortran
      if: matrix.os == 'ubuntu-latest'

    - name: macos install fortran
      run: |
        python -m pip install --upgrade pip
        pip install numpy wheel
        alias gfortran=gfortran-8
        gfortran -v
        pip install .
      if: matrix.os == 'macos-10.15'

    - name: windows install fortran
      run: |
        choco install mingw
        pip install numpy==1.15
      if: matrix.os == 'windows-latest'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install . 
        pip install -r requirements-test.txt
    - name: Test with pytest
      run: |
        pip install pytest
        pytest tests/
