name: gripy Unit Tests

on: [push]

jobs:
  unit_tests:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [  macos-10.15 ]
        python: [ 3.8, ]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}

    - name: ubuntu install fortran
      run: sudo apt install gfortran
      if: matrix.os == 'ubuntu-latest'

    - name: Fix Conda permissions on macOS
      run: |
        sudo chown -R $UID $CONDA
        echo $SHELL
        $CONDA/bin/conda init bash
      if: matrix.os == 'macos-10.15'

    - name: macos install dependencies
      run: |
        $CONDA/bin/conda install gfortran_osx-64 numpy wheel
        ln -s $CONDA/bin/gfortran /usr/local/bin/gfortran
        $CONDA/bin/python -m pip install .
        $CONDA/bin/python -m pip install -r requirements-test.txt
      if: matrix.os == 'macos-10.15'

    - name: macos run tests
      run: $CONDA/bin/pytest tests/
      if: matrix.os == 'macos-10.15'

    - name: Build wheels
      env:
        # CIBW_BEFORE_BUILD: scripts/build-openssl /tmp/vendor
        CIBW_ENVIRONMENT: "PATH=$PATH:$CONDA/bin"
        CIBW_SKIP: cp27-* cp33-* cp34-* cp35-* pp27-*
        # CIBW_TEST_COMMAND: $CONDA/bin/pytest discover -t {project} -s {project}/tests
      run: |
        $CONDA/bin/pip install cibuildwheel
        $CONDA/bin/cibuildwheel --output-dir ./wheelhouse
      shell: bash
    - uses: actions/upload-artifact@v2
      with:
        name: 'Artifacts-V2'
        path: './wheelhouse'
      if: matrix.os == 'macos-10.15'

    - name: windows install fortran
      run: |
        choco install mingw
        pip install numpy==1.15
      if: matrix.os == 'windows-latest'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .
        pip install -r requirements-test.txt
      if: matrix.os != 'macos-10.15'

    - name: Test with pytest
      run: |
        pip install pytest
        pytest tests/
      if: matrix.os != 'macos-10.15'
